### PR TITLE
Add docker instructions

### PR DESCRIPTION
**Pull request by deepsadhi**
Added `Dockerfile` by taking reference from [Triton Dockerfile](https://github.com/JonathanSalwan/Triton/blob/master/Dockerfilel). In addition to `Triton` installation, packages `arybo` and `lief` are installed using `pip`.

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
What about `llvmlite` (#6) ?

**Comment by deepsadhi** [comment]
I have added command to install `llvmlite` using `pip`.

**Comment by JonathanSalwan** [comment]
Can you fix the Triton's version with this commit instead of master? https://github.com/JonathanSalwan/Triton/archive/2838b732d6398b33f590f4db5d045c26054486ae.zip

thanks,

**Comment by deepsadhi** [comment]
Sorry! I could not get you. Do you want me send the PR to repo [JonathanSalwan/Triton](https://github.com/JonathanSalwan/Triton)? Could you please send me detail instructions.

**Comment by JonathanSalwan** [comment]
Replace the lines 30 to 32 of your Dockerfile by these following ones in order to fix the Triton's version instead of using `master`. Otherwise, I will always have to fix `solve-vm.py` when the Triton's API will change:

```bash
RUN cd /opt/pin-2.14-71313-gcc.4.4.7-linux/source/tools/ && \
    curl -o triton.zip -L https://github.com/JonathanSalwan/Triton/archive/2838b732d6398b33f590f4db5d045c26054486ae.zip && \\
    unzip triton.zip && cd Triton-2838b732d6398b33f590f4db5d045c26054486ae/ && mkdir build && cd build && \\
    cmake -G "Unix Makefiles" -DPINTOOL=on -DKERNEL4=on .. && make install && cd ..
```

After this change, I will merge your PR :). Thanks for this dockerfile!

**Comment by deepsadhi** [comment]
Done :+1:

**Comment by deepsadhi** [comment]
@JonathanSalwan could you please merge this PR.

**Pull request merged**
